chain=testnet4

[testnet4]
# https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L564 (testnet4 uses port 48333)
port=48333
# https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L683
rpcbind=0.0.0.0
# https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L688 (testnet4 uses RPC port 48332)
rpcport=48332
# https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L691
rpcuser=bobby
# https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L691
rpcpassword=bobby
# https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L695
server=1
# https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L528
txindex=1
# https://github.com/bitcoin/bitcoin/blob/master/src/wallet/init.cpp#L46
addresstype=bech32
# https://github.com/bitcoin/bitcoin/blob/master/src/wallet/init.cpp#L48
changetype=bech32
# https://github.com/bitcoin/bitcoin/blob/master/src/init/common.cpp#L34
logips=1
# https://github.com/bitcoin/bitcoin/blob/master/src/init/common.cpp#L37
logthreadnames=1
# https://github.com/bitcoin/bitcoin/blob/master/src/init/common.cpp#L36
logtimestamps=1
# https://github.com/bitcoin/bitcoin/blob/master/src/init/common.cpp#L42
nodebuglogfile=1
# https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L680
rest=1
# https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp#L683
rpcallowip=0.0.0.0/0
