/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountlessApplication {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "publishable_key")]
    pub publishable_key: String,
    #[serde(rename = "secret_key", skip_serializing_if = "Option::is_none")]
    pub secret_key: Option<String>,
    #[serde(rename = "claim_url", skip_serializing_if = "Option::is_none")]
    pub claim_url: Option<String>,
    #[serde(rename = "api_keys_url", skip_serializing_if = "Option::is_none")]
    pub api_keys_url: Option<String>,
}

impl AccountlessApplication {
    pub fn new(object: Object, publishable_key: String) -> AccountlessApplication {
        AccountlessApplication {
            object,
            publishable_key,
            secret_key: None,
            claim_url: None,
            api_keys_url: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "accountless_application")]
    AccountlessApplication,
}

impl Default for Object {
    fn default() -> Object {
        Self::AccountlessApplication
    }
}
