/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwsCredential {
    #[serde(rename = "id")]
    pub id: String,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "access_key_id")]
    pub access_key_id: String,
    #[serde(rename = "user_pool_ids")]
    pub user_pool_ids: Vec<String>,
    /// Unix timestamp of creation
    #[serde(rename = "created_at")]
    pub created_at: i64,
    /// Unix timestamp of creation
    #[serde(rename = "updated_at")]
    pub updated_at: i64,
}

impl AwsCredential {
    pub fn new(
        id: String,
        object: Object,
        access_key_id: String,
        user_pool_ids: Vec<String>,
        created_at: i64,
        updated_at: i64,
    ) -> AwsCredential {
        AwsCredential {
            id,
            object,
            access_key_id,
            user_pool_ids,
            created_at,
            updated_at,
        }
    }
}
/// String representing the object's type. Objects of the same type share the same value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "aws_credential")]
    AwsCredential,
}

impl Default for Object {
    fn default() -> Object {
        Self::AwsCredential
    }
}
