/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClerkError {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "long_message")]
    pub long_message: String,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<serde_json::Value>,
    #[serde(rename = "clerk_trace_id", skip_serializing_if = "Option::is_none")]
    pub clerk_trace_id: Option<String>,
}

impl ClerkError {
    pub fn new(message: String, long_message: String, code: String) -> ClerkError {
        ClerkError {
            message,
            long_message,
            code,
            meta: None,
            clerk_trace_id: None,
        }
    }
}
