/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommerceSubscriptionItemNextPaymentResponse {
    /// Amount for the next payment.
    #[serde(
        rename = "amount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub amount: Option<Option<Box<models::CommerceMoneyResponse>>>,
    /// Unix timestamp (in milliseconds) for the next payment date.
    #[serde(
        rename = "date",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub date: Option<Option<i64>>,
}

impl CommerceSubscriptionItemNextPaymentResponse {
    pub fn new() -> CommerceSubscriptionItemNextPaymentResponse {
        CommerceSubscriptionItemNextPaymentResponse {
            amount: None,
            date: None,
        }
    }
}
