/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSignInTokenRequest {
    /// The ID of the user that can use the newly created sign in token
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// Optional parameter to specify the life duration of the sign in token in seconds. By default, the duration is 30 days.
    #[serde(
        rename = "expires_in_seconds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_in_seconds: Option<Option<i32>>,
}

impl CreateSignInTokenRequest {
    pub fn new(user_id: String) -> CreateSignInTokenRequest {
        CreateSignInTokenRequest {
            user_id,
            expires_in_seconds: None,
        }
    }
}
