/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrganizationMembershipRequest {
    /// The ID of the user that will be added as a member in the organization. The user needs to exist in the same instance as the organization and must not be a member of the given organization already.
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// The role that the new member will have in the organization.
    #[serde(rename = "role")]
    pub role: String,
}

impl CreateOrganizationMembershipRequest {
    pub fn new(user_id: String, role: String) -> CreateOrganizationMembershipRequest {
        CreateOrganizationMembershipRequest { user_id, role }
    }
}
