/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "object")]
pub enum EmailAddressVerification {
    #[serde(rename = "verification_otp")]
    VerificationOtp(Box<models::VerificationOtp>),
    #[serde(rename = "verification_admin")]
    VerificationAdmin(Box<models::VerificationAdmin>),
    #[serde(rename = "verification_from_oauth")]
    VerificationFromOauth(Box<models::VerificationFromOauth>),
    #[serde(rename = "verification_ticket")]
    VerificationTicket(Box<models::VerificationTicket>),
    #[serde(rename = "verification_saml")]
    VerificationSaml(Box<models::VerificationSaml>),
    #[serde(rename = "verification_email_link")]
    VerificationEmailLink(Box<models::VerificationEmailLink>),
}

impl Default for EmailAddressVerification {
    fn default() -> Self {
        Self::VerificationOtp(Default::default())
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "unverified")]
    Unverified,
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "expired")]
    Expired,
}

impl Default for Status {
    fn default() -> Status {
        Self::Unverified
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Strategy {
    #[serde(rename = "email_link")]
    EmailLink,
}

impl Default for Strategy {
    fn default() -> Strategy {
        Self::EmailLink
    }
}
