/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetM2MTokens400Response {
    #[serde(rename = "errors")]
    pub errors: Vec<models::GetM2MTokens400ResponseErrorsInner>,
}

impl GetM2MTokens400Response {
    pub fn new(errors: Vec<models::GetM2MTokens400ResponseErrorsInner>) -> GetM2MTokens400Response {
        GetM2MTokens400Response { errors }
    }
}
