/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Instance {
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "environment_type")]
    pub environment_type: String,
    #[serde(rename = "allowed_origins", deserialize_with = "Option::deserialize")]
    pub allowed_origins: Option<Vec<String>>,
}

impl Instance {
    pub fn new(
        object: Object,
        id: String,
        environment_type: String,
        allowed_origins: Option<Vec<String>>,
    ) -> Instance {
        Instance {
            object,
            id,
            environment_type,
            allowed_origins,
        }
    }
}
/// String representing the object's type. Objects of the same type share the same value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "instance")]
    Instance,
}

impl Default for Object {
    fn default() -> Object {
        Self::Instance
    }
}
