/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationSettings {
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "max_allowed_memberships")]
    pub max_allowed_memberships: i32,
    #[serde(rename = "max_allowed_roles")]
    pub max_allowed_roles: i32,
    /// max_allowed_permissions is now a no-op, as permissions are now unlimited
    #[serde(
        rename = "max_allowed_permissions",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_allowed_permissions: Option<i32>,
    /// The role key that a user will be assigned after creating an organization.
    #[serde(rename = "creator_role")]
    pub creator_role: String,
    /// The default for whether an admin can delete an organization with the Frontend API.
    #[serde(rename = "admin_delete_enabled")]
    pub admin_delete_enabled: bool,
    #[serde(rename = "domains_enabled")]
    pub domains_enabled: bool,
    #[serde(rename = "domains_enrollment_modes")]
    pub domains_enrollment_modes: Vec<DomainsEnrollmentModes>,
    /// The role key that it will be used in order to create an organization invitation or suggestion.
    #[serde(rename = "domains_default_role")]
    pub domains_default_role: String,
}

impl OrganizationSettings {
    pub fn new(
        object: Object,
        enabled: bool,
        max_allowed_memberships: i32,
        max_allowed_roles: i32,
        creator_role: String,
        admin_delete_enabled: bool,
        domains_enabled: bool,
        domains_enrollment_modes: Vec<DomainsEnrollmentModes>,
        domains_default_role: String,
    ) -> OrganizationSettings {
        OrganizationSettings {
            object,
            enabled,
            max_allowed_memberships,
            max_allowed_roles,
            max_allowed_permissions: None,
            creator_role,
            admin_delete_enabled,
            domains_enabled,
            domains_enrollment_modes,
            domains_default_role,
        }
    }
}
/// String representing the object's type. Objects of the same type share the same value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "organization_settings")]
    OrganizationSettings,
}

impl Default for Object {
    fn default() -> Object {
        Self::OrganizationSettings
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DomainsEnrollmentModes {
    #[serde(rename = "manual_invitation")]
    ManualInvitation,
    #[serde(rename = "automatic_invitation")]
    AutomaticInvitation,
    #[serde(rename = "automatic_suggestion")]
    AutomaticSuggestion,
}

impl Default for DomainsEnrollmentModes {
    fn default() -> DomainsEnrollmentModes {
        Self::ManualInvitation
    }
}
