/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SchemasSamlConnection {
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(rename = "domains", skip_serializing_if = "Option::is_none")]
    pub domains: Option<Vec<String>>,
    #[serde(rename = "idp_entity_id", deserialize_with = "Option::deserialize")]
    pub idp_entity_id: Option<String>,
    #[serde(rename = "idp_sso_url", deserialize_with = "Option::deserialize")]
    pub idp_sso_url: Option<String>,
    #[serde(rename = "idp_certificate", deserialize_with = "Option::deserialize")]
    pub idp_certificate: Option<String>,
    #[serde(
        rename = "idp_metadata_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub idp_metadata_url: Option<Option<String>>,
    #[serde(
        rename = "idp_metadata",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub idp_metadata: Option<Option<String>>,
    #[serde(rename = "acs_url")]
    pub acs_url: String,
    #[serde(rename = "sp_entity_id")]
    pub sp_entity_id: String,
    #[serde(rename = "sp_metadata_url")]
    pub sp_metadata_url: String,
    #[serde(
        rename = "organization_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_id: Option<Option<String>>,
    #[serde(rename = "attribute_mapping", skip_serializing_if = "Option::is_none")]
    pub attribute_mapping: Option<Box<models::SamlConnectionAttributeMapping>>,
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "user_count")]
    pub user_count: i32,
    #[serde(rename = "sync_user_attributes")]
    pub sync_user_attributes: bool,
    #[serde(rename = "allow_subdomains", skip_serializing_if = "Option::is_none")]
    pub allow_subdomains: Option<bool>,
    #[serde(
        rename = "allow_idp_initiated",
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_idp_initiated: Option<bool>,
    #[serde(
        rename = "disable_additional_identifications",
        skip_serializing_if = "Option::is_none"
    )]
    pub disable_additional_identifications: Option<bool>,
    /// Unix timestamp of creation.
    #[serde(rename = "created_at")]
    pub created_at: i64,
    /// Unix timestamp of last update.
    #[serde(rename = "updated_at")]
    pub updated_at: i64,
}

impl SchemasSamlConnection {
    pub fn new(
        object: Object,
        id: String,
        name: String,
        idp_entity_id: Option<String>,
        idp_sso_url: Option<String>,
        idp_certificate: Option<String>,
        acs_url: String,
        sp_entity_id: String,
        sp_metadata_url: String,
        active: bool,
        provider: String,
        user_count: i32,
        sync_user_attributes: bool,
        created_at: i64,
        updated_at: i64,
    ) -> SchemasSamlConnection {
        SchemasSamlConnection {
            object,
            id,
            name,
            domain: None,
            domains: None,
            idp_entity_id,
            idp_sso_url,
            idp_certificate,
            idp_metadata_url: None,
            idp_metadata: None,
            acs_url,
            sp_entity_id,
            sp_metadata_url,
            organization_id: None,
            attribute_mapping: None,
            active,
            provider,
            user_count,
            sync_user_attributes,
            allow_subdomains: None,
            allow_idp_initiated: None,
            disable_additional_identifications: None,
            created_at,
            updated_at,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "saml_connection")]
    SamlConnection,
}

impl Default for Object {
    fn default() -> Object {
        Self::SamlConnection
    }
}
