/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAwsCredentialRequest {
    #[serde(
        rename = "access_key_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub access_key_id: Option<Option<String>>,
    #[serde(rename = "user_pool_ids", skip_serializing_if = "Option::is_none")]
    pub user_pool_ids: Option<Vec<String>>,
    #[serde(
        rename = "secret_access_key",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub secret_access_key: Option<Option<String>>,
}

impl UpdateAwsCredentialRequest {
    pub fn new() -> UpdateAwsCredentialRequest {
        UpdateAwsCredentialRequest {
            access_key_id: None,
            user_pool_ids: None,
            secret_access_key: None,
        }
    }
}
