/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateOrganizationRequest {
    /// Metadata saved on the organization, that is visible to both your frontend and backend.
    #[serde(
        rename = "public_metadata",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub public_metadata: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    /// Metadata saved on the organization that is only visible to your backend.
    #[serde(
        rename = "private_metadata",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub private_metadata: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    /// The new name of the organization. May not contain URLs or HTML. Max length: 256
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    /// The new slug of the organization, which needs to be unique in the instance
    #[serde(
        rename = "slug",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub slug: Option<Option<String>>,
    /// The maximum number of memberships allowed for this organization
    #[serde(
        rename = "max_allowed_memberships",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_allowed_memberships: Option<Option<i32>>,
    /// If true, an admin can delete this organization with the Frontend API.
    #[serde(
        rename = "admin_delete_enabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub admin_delete_enabled: Option<Option<bool>>,
    /// A custom date/time denoting _when_ the organization was created, specified in RFC3339 format (e.g. `2012-10-20T07:15:20.902Z`).
    #[serde(
        rename = "created_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created_at: Option<Option<String>>,
}

impl UpdateOrganizationRequest {
    pub fn new() -> UpdateOrganizationRequest {
        UpdateOrganizationRequest {
            public_metadata: None,
            private_metadata: None,
            name: None,
            slug: None,
            max_allowed_memberships: None,
            admin_delete_enabled: None,
            created_at: None,
        }
    }
}
