/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateEmailAddressRequest {
    /// The email address will be marked as verified.
    #[serde(
        rename = "verified",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub verified: Option<Option<bool>>,
    /// Set this email address as the primary email address for the user.
    #[serde(
        rename = "primary",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary: Option<Option<bool>>,
}

impl UpdateEmailAddressRequest {
    pub fn new() -> UpdateEmailAddressRequest {
        UpdateEmailAddressRequest {
            verified: None,
            primary: None,
        }
    }
}
