[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "100.0.0"
edition = "2024"

[workspace.dependencies]
ahash = "0.8.3"
anyhow = "1"
argon2 = { version = "0.5.2", features = ["alloc"] }
async-trait = "0.1.74"
bitcoincore-rpc-json = { git = "https://github.com/rust-bitcoin/rust-bitcoincore-rpc", package = "bitcoincore-rpc-json" }
bytemuck = "1"
chrono = "0.4.31"
clap = { version = "4", features = ["derive", "env"] }
dotenv = "0.15.0"
ethers = { version = "2.0.10", features = ["ws"] }
futures = "0.3.28"
http-body-util = "0.1.3"
itertools = "0.14"
jsonrpc-async = "2.0.2"
jsonwebtoken = "9"
mime = "0.3.17"
mime_guess = "2.0.5"
prost = "0.12.1"
rand = "0.8.5"
reqwest = { version = "0.11.22", features = ["json", "blocking"] }
rmp = "0.8.12"
rmp-serde = "1"
rustc-hex = "2.1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10.8"
thiserror = "2"
time = "0.3.36"
tinyvec = { version = "1", features = ["rustc_1_61", "std", "alloc"] }
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.20.1", features = ["native-tls-vendored"] }
toml = "0.9"
tonic = "0.10.2"
tonic-reflection = "0.10.2"
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.5.2", features = ["full"] }
tracing = "0.1.37"
uuid = { version = "1", features = ["v4", "serde", "zerocopy", "fast-rng"] }

[workspace.dependencies.rust_decimal]
version = "1"
features = [
    "macros",
    "serde",
    "serde-with-str",
]

[workspace.dependencies.tracing-subscriber]
version = "0.3"
features = ["env-filter", "fmt", "json", "std"]

[workspace.dependencies.bitcoin]
version = "0.30.1"
features = ["rand", "serde", "base64", "bitcoinconsensus", "core2"]

[workspace.dependencies.sqlx]
version = "0.7.2"
default-features = false
features = [
    "postgres",
    "tls-native-tls",
    "rust_decimal",
    "runtime-tokio",
    "macros",
    "migrate",
    "uuid",
    "time",
    "json",
]

[workspace.dependencies.axum]
version = "0.7"
default-features = false
features = [
    "http1",
    "tracing",
    "ws",
    "macros",
    "matched-path",
    "multipart",
    "original-uri",
    "tokio",
    "tower-log",
    "query",
    "json",
    "form",
]
