services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - exchange-net
    environment:
      - NODE_ENV=production
    restart: on-failure
    stop_signal: SIGINT

  exchange:
    image: exchange-orderbook:latest
    build:
      context: .
      dockerfile: crates/common-core/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./etc/exchange/conf.toml:/etc/exchange/conf.toml
    networks:
      - exchange-net
    environment:
      - DATABASE_URL=postgres://exchange_user:exchange_password@postgres:5432/exchange
      - RUST_LOG=debug
      - CONFIG_FILE_PATH=/etc/exchange/conf.toml
      - BITCOIN_RPC_URL=http://bitcoind:8332
    depends_on:
      - postgres
      - bitcoind
      - bitcoind-grpc-proxy
    restart: on-failure # Restart the service if it fails
    stop_signal: SIGINT # Stop the service gracefully

  bitcoind-grpc-proxy:
    image: exchange-orderbook:latest
    build:
      context: .
      dockerfile: crates/common-core/Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ./etc/exchange/conf.toml:/etc/exchange/conf.toml
    networks:
      - exchange-net
    environment:
      - RUST_LOG="info"
      - DATABASE_URL=postgres://exchange_user:exchange_password@postgres:5432/exchange
      - CONFIG_FILE_PATH=/etc/exchange/conf.toml
      - BITCOIN_RPC_URL=http://bitcoind:8332
    depends_on:
      - bitcoind
    command: ["/usr/local/bin/bitcoind-grpc"]
    restart: on-failure # Restart the service if it fails
    stop_signal: SIGINT # Stop the service gracefully

  nginx: # Commented out for local development - use direct access instead
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/letsencrypt/:/etc/letsencrypt:ro
    networks:
      - exchange-net
    depends_on:
      - frontend
      - exchange

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - exchange-net
    environment:
      - POSTGRES_DB=exchange
      - POSTGRES_USER=exchange_user
      - POSTGRES_PASSWORD=exchange_password
      - TZ=UTC
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  bitcoind:
    image: lncm/bitcoind:v25.0
    user: 1000:1000
    volumes:
      - ./etc/bitcoin:/data/.bitcoin
    restart: on-failure
    stop_grace_period: 15m30s
    ports:
      - "8333:8333"
      - "8332:8332"
      - "28332:28332"
      - "28333:28333"
    networks:
      - exchange-net

networks:
  exchange-net:
    driver: bridge

volumes:
  postgres-data:
