services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3001:3000"
    networks:
      - exchange-net
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
    restart: on-failure:3
    stop_signal: SIGINT

  backend:
    image: exchange-orderbook:latest
    build:
      context: .
      dockerfile: crates/matching_engine/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - exchange-net
    environment:
      - DATABASE_URL=postgres://exchange_user:exchange_password@postgres:5432/exchange
      - RUST_LOG=info,exchange=trace,tower_http=debug
      - CONFIG_FILE_PATH=/etc/exchange/conf.toml
      - BITCOIN_RPC_URL=http://bitcoind:8332
      - TRADING_BIND_ADDRESS="0.0.0.0:7777"
      - BITCOIN_GRPC_ENDPOINT="http://bitcoind-grpc-proxy:50051"
    depends_on:
      - postgres
      - bitcoind
      - bitcoind-grpc-proxy
    restart: on-failure:3
    stop_signal: SIGINT # Stop the service gracefully

  bitcoind-grpc-proxy:
    image: exchange-orderbook:latest
    build:
      context: .
      dockerfile: crates/common-core/Dockerfile
    ports:
      - "50051:50051"
    networks:
      - exchange-net
    environment:
      - RUST_LOG="info"
      - DATABASE_URL=postgres://exchange_user:exchange_password@postgres:5432/exchange
      - BITCOIN_RPC_URL=http://bitcoind:8332
      - INFURA_WS="wss://goerli.infura.io/ws/v3/15420f8445614737ba63730cbc019cf2"
      - BITCOIN_RPC_AUTH_USER="bobby"
      - BITCOIN_RPC_AUTH_PASSWORD="bobby"
      - BITCOIN_WALLET_NAME="org.exchange.wallet"
    depends_on:
      - bitcoind
    command: ["/usr/local/bin/bitcoind-grpc"]
    restart: on-failure # Restart the service if it fails
    stop_signal: SIGINT # Stop the service gracefully

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/letsencrypt/:/etc/letsencrypt:ro
    networks:
      - exchange-net
    depends_on:
      - frontend
      - backend

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - exchange-net
    environment:
      - POSTGRES_DB=exchange
      - POSTGRES_USER=exchange_user
      - POSTGRES_PASSWORD=exchange_password
      - TZ=UTC
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure

  bitcoind:
    image: lncm/bitcoind:v28.0
    user: 1000:1000
    volumes:
      - ./etc/bitcoin:/data/.bitcoin
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "8333:8333"
      - "8332:8332"
      - "28332:28332"
      - "28333:28333"
    networks:
      - exchange-net

networks:
  exchange-net:
    driver: bridge

volumes:
  postgres-data:
