events {
  worker_connections 1024;
}

http {
  include mime.types;

  server_tokens off;

  resolver 127.0.0.11 valid=10s;

  upstream backend {
    server exchange:3000;
  }
  upstream frontend {
    server frontend:3000;
  }

  server {
    listen 80;

    location / {
      return 301 https://$host$request_uri;
    }
  }

  server {
    listen 443 ssl;
    server_name localhost;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    # add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; " always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    # add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer" always;

    ssl_certificate /etc/letsencrypt/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location /api/ {
      proxy_pass http://backend;
    }

    # Static assets go to Next.js
    location ~ ^/(_next|__next) {
      proxy_pass http://frontend;
    }

    # Everything else goes to Next.js frontend
    location / {
      proxy_pass http://frontend;
    }
  }
}
