/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use super::configuration;
use super::Error;
use crate::apis::ContentType;
use crate::apis::ResponseContent;
use crate::models;
use async_trait::async_trait;
use reqwest;
use serde::de::Error as _;
use serde::Deserialize;
use serde::Serialize;
use std::sync::Arc;

#[async_trait]
pub trait M2MTokensApi: Send + Sync {
    /// POST /m2m_tokens
    ///
    /// Creates a new M2M Token. Must be authenticated via a Machine Secret Key.
    async fn create_m2_m_token<'create_m2_m_token_request>(
        &self,
        create_m2_m_token_request: models::CreateM2MTokenRequest,
    ) -> Result<models::CreateM2MToken201Response, Error<CreateM2MTokenError>>;

    /// GET /m2m_tokens
    ///
    /// Fetches M2M tokens for a specific machine.  This endpoint can be authenticated by either a Machine Secret Key or by a Clerk Secret Key.  - When fetching M2M tokens with a Machine Secret Key, only tokens associated with the authenticated machine can be retrieved. - When fetching M2M tokens with a Clerk Secret Key, tokens for any machine in the instance can be retrieved.
    async fn get_m2_m_tokens<'subject, 'revoked, 'expired, 'limit, 'offset>(
        &self,
        subject: &'subject str,
        revoked: Option<bool>,
        expired: Option<bool>,
        limit: Option<f64>,
        offset: Option<f64>,
    ) -> Result<models::GetM2MTokens200Response, Error<GetM2MTokensError>>;

    /// POST /m2m_tokens/{m2m_token_id}/revoke
    ///
    /// Revokes a M2M Token.  This endpoint can be authenticated by either a Machine Secret Key or by a Clerk Secret Key.  - When revoking a M2M Token with a Machine Secret Key, the token must managed by the Machine associated with the Machine Secret Key. - When revoking a M2M Token with a Clerk Secret Key, any token on the Instance can be revoked.
    async fn revoke_m2_m_token<'m2m_token_id, 'revoke_m2_m_token_request>(
        &self,
        m2m_token_id: &'m2m_token_id str,
        revoke_m2_m_token_request: models::RevokeM2MTokenRequest,
    ) -> Result<models::GetM2MTokens200ResponseM2mTokensInner, Error<RevokeM2MTokenError>>;

    /// POST /m2m_tokens/verify
    ///
    /// Verifies a M2M Token.  This endpoint can be authenticated by either a Machine Secret Key or by a Clerk Secret Key.  - When verifying a M2M Token with a Machine Secret Key, the token must be granted access to the Machine associated with the Machine Secret Key. - When verifying a M2M Token with a Clerk Secret Key, any token on the Instance can be verified.
    async fn verify_m2_m_token<'verify_m2_m_token_request>(
        &self,
        verify_m2_m_token_request: models::VerifyM2MTokenRequest,
    ) -> Result<models::GetM2MTokens200ResponseM2mTokensInner, Error<VerifyM2MTokenError>>;
}

pub struct M2MTokensApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl M2MTokensApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl M2MTokensApi for M2MTokensApiClient {
    /// Creates a new M2M Token. Must be authenticated via a Machine Secret Key.
    async fn create_m2_m_token<'create_m2_m_token_request>(
        &self,
        create_m2_m_token_request: models::CreateM2MTokenRequest,
    ) -> Result<models::CreateM2MToken201Response, Error<CreateM2MTokenError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/m2m_tokens", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&create_m2_m_token_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateM2MToken201Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::CreateM2MToken201Response`")))),
            }
        } else {
            let local_var_entity: Option<CreateM2MTokenError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Fetches M2M tokens for a specific machine.  This endpoint can be authenticated by either a Machine Secret Key or by a Clerk Secret Key.  - When fetching M2M tokens with a Machine Secret Key, only tokens associated with the authenticated machine can be retrieved. - When fetching M2M tokens with a Clerk Secret Key, tokens for any machine in the instance can be retrieved.
    async fn get_m2_m_tokens<'subject, 'revoked, 'expired, 'limit, 'offset>(
        &self,
        subject: &'subject str,
        revoked: Option<bool>,
        expired: Option<bool>,
        limit: Option<f64>,
        offset: Option<f64>,
    ) -> Result<models::GetM2MTokens200Response, Error<GetM2MTokensError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/m2m_tokens", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        local_var_req_builder = local_var_req_builder.query(&[("subject", &subject.to_string())]);
        if let Some(ref param_value) = revoked {
            local_var_req_builder =
                local_var_req_builder.query(&[("revoked", &param_value.to_string())]);
        }
        if let Some(ref param_value) = expired {
            local_var_req_builder =
                local_var_req_builder.query(&[("expired", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetM2MTokens200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::GetM2MTokens200Response`")))),
            }
        } else {
            let local_var_entity: Option<GetM2MTokensError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Revokes a M2M Token.  This endpoint can be authenticated by either a Machine Secret Key or by a Clerk Secret Key.  - When revoking a M2M Token with a Machine Secret Key, the token must managed by the Machine associated with the Machine Secret Key. - When revoking a M2M Token with a Clerk Secret Key, any token on the Instance can be revoked.
    async fn revoke_m2_m_token<'m2m_token_id, 'revoke_m2_m_token_request>(
        &self,
        m2m_token_id: &'m2m_token_id str,
        revoke_m2_m_token_request: models::RevokeM2MTokenRequest,
    ) -> Result<models::GetM2MTokens200ResponseM2mTokensInner, Error<RevokeM2MTokenError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/m2m_tokens/{m2m_token_id}/revoke",
            local_var_configuration.base_path,
            m2m_token_id = crate::apis::urlencode(m2m_token_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&revoke_m2_m_token_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetM2MTokens200ResponseM2mTokensInner`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::GetM2MTokens200ResponseM2mTokensInner`")))),
            }
        } else {
            let local_var_entity: Option<RevokeM2MTokenError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Verifies a M2M Token.  This endpoint can be authenticated by either a Machine Secret Key or by a Clerk Secret Key.  - When verifying a M2M Token with a Machine Secret Key, the token must be granted access to the Machine associated with the Machine Secret Key. - When verifying a M2M Token with a Clerk Secret Key, any token on the Instance can be verified.
    async fn verify_m2_m_token<'verify_m2_m_token_request>(
        &self,
        verify_m2_m_token_request: models::VerifyM2MTokenRequest,
    ) -> Result<models::GetM2MTokens200ResponseM2mTokensInner, Error<VerifyM2MTokenError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/m2m_tokens/verify", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&verify_m2_m_token_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetM2MTokens200ResponseM2mTokensInner`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::GetM2MTokens200ResponseM2mTokensInner`")))),
            }
        } else {
            let local_var_entity: Option<VerifyM2MTokenError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`M2MTokensApi::create_m2_m_token`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateM2MTokenError {
    Status400(models::GetM2MTokens400Response),
    Status409(models::GetM2MTokens403Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`M2MTokensApi::get_m2_m_tokens`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetM2MTokensError {
    Status400(models::GetM2MTokens400Response),
    Status403(models::GetM2MTokens403Response),
    Status404(models::GetM2MTokens403Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`M2MTokensApi::revoke_m2_m_token`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RevokeM2MTokenError {
    Status400(models::GetM2MTokens400Response),
    Status404(models::GetM2MTokens403Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`M2MTokensApi::verify_m2_m_token`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VerifyM2MTokenError {
    Status400(models::GetM2MTokens400Response),
    Status404(models::GetM2MTokens403Response),
    UnknownValue(serde_json::Value),
}
