/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use super::configuration;
use super::Error;
use crate::apis::ContentType;
use crate::apis::ResponseContent;
use crate::models;
use async_trait::async_trait;
use reqwest;
use serde::de::Error as _;
use serde::Deserialize;
use serde::Serialize;
use std::sync::Arc;

#[async_trait]
pub trait OrganizationDomainsApi: Send + Sync {
    /// POST /organizations/{organization_id}/domains
    ///
    /// Creates a new organization domain. By default the domain is verified, but can be optionally set to unverified.
    async fn create_organization_domain<'organization_id, 'create_organization_domain_request>(
        &self,
        organization_id: &'organization_id str,
        create_organization_domain_request: models::CreateOrganizationDomainRequest,
    ) -> Result<models::OrganizationDomain, Error<CreateOrganizationDomainError>>;

    /// DELETE /organizations/{organization_id}/domains/{domain_id}
    ///
    /// Removes the given domain from the organization.
    async fn delete_organization_domain<'organization_id, 'domain_id>(
        &self,
        organization_id: &'organization_id str,
        domain_id: &'domain_id str,
    ) -> Result<models::DeletedObject, Error<DeleteOrganizationDomainError>>;

    /// GET /organization_domains
    ///
    /// Retrieves a list of all organization domains within the current instance. This endpoint can be used to list all domains across all organizations or filter domains by organization, verification status, enrollment mode, or search query.  The response includes pagination information and details about each domain including its verification status, enrollment mode, and associated counts.
    async fn list_all_organization_domains<
        'organization_id,
        'verified,
        'enrollment_mode,
        'query,
        'order_by,
        'offset,
        'limit,
    >(
        &self,
        organization_id: Option<&'organization_id str>,
        verified: Option<&'verified str>,
        enrollment_mode: Option<Vec<String>>,
        query: Option<&'query str>,
        order_by: Option<&'order_by str>,
        offset: Option<i32>,
        limit: Option<i32>,
    ) -> Result<models::OrganizationDomains, Error<ListAllOrganizationDomainsError>>;

    /// GET /organizations/{organization_id}/domains
    ///
    /// Get a list of all domains of an organization.
    async fn list_organization_domains<
        'organization_id,
        'verified,
        'enrollment_mode,
        'limit,
        'offset,
    >(
        &self,
        organization_id: &'organization_id str,
        verified: Option<&'verified str>,
        enrollment_mode: Option<&'enrollment_mode str>,
        limit: Option<i32>,
        offset: Option<i32>,
    ) -> Result<models::OrganizationDomains, Error<ListOrganizationDomainsError>>;

    /// PATCH /organizations/{organization_id}/domains/{domain_id}
    ///
    /// Updates the properties of an existing organization domain.
    async fn update_organization_domain<
        'organization_id,
        'domain_id,
        'update_organization_domain_request,
    >(
        &self,
        organization_id: &'organization_id str,
        domain_id: &'domain_id str,
        update_organization_domain_request: models::UpdateOrganizationDomainRequest,
    ) -> Result<models::OrganizationDomain, Error<UpdateOrganizationDomainError>>;
}

pub struct OrganizationDomainsApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl OrganizationDomainsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl OrganizationDomainsApi for OrganizationDomainsApiClient {
    /// Creates a new organization domain. By default the domain is verified, but can be optionally set to unverified.
    async fn create_organization_domain<'organization_id, 'create_organization_domain_request>(
        &self,
        organization_id: &'organization_id str,
        create_organization_domain_request: models::CreateOrganizationDomainRequest,
    ) -> Result<models::OrganizationDomain, Error<CreateOrganizationDomainError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organization_id}/domains",
            local_var_configuration.base_path,
            organization_id = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&create_organization_domain_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganizationDomain`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OrganizationDomain`")))),
            }
        } else {
            let local_var_entity: Option<CreateOrganizationDomainError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Removes the given domain from the organization.
    async fn delete_organization_domain<'organization_id, 'domain_id>(
        &self,
        organization_id: &'organization_id str,
        domain_id: &'domain_id str,
    ) -> Result<models::DeletedObject, Error<DeleteOrganizationDomainError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organization_id}/domains/{domain_id}",
            local_var_configuration.base_path,
            organization_id = crate::apis::urlencode(organization_id),
            domain_id = crate::apis::urlencode(domain_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeletedObject`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::DeletedObject`")))),
            }
        } else {
            let local_var_entity: Option<DeleteOrganizationDomainError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves a list of all organization domains within the current instance. This endpoint can be used to list all domains across all organizations or filter domains by organization, verification status, enrollment mode, or search query.  The response includes pagination information and details about each domain including its verification status, enrollment mode, and associated counts.
    async fn list_all_organization_domains<
        'organization_id,
        'verified,
        'enrollment_mode,
        'query,
        'order_by,
        'offset,
        'limit,
    >(
        &self,
        organization_id: Option<&'organization_id str>,
        verified: Option<&'verified str>,
        enrollment_mode: Option<Vec<String>>,
        query: Option<&'query str>,
        order_by: Option<&'order_by str>,
        offset: Option<i32>,
        limit: Option<i32>,
    ) -> Result<models::OrganizationDomains, Error<ListAllOrganizationDomainsError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str =
            format!("{}/organization_domains", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = organization_id {
            local_var_req_builder =
                local_var_req_builder.query(&[("organization_id", &param_value.to_string())]);
        }
        if let Some(ref param_value) = verified {
            local_var_req_builder =
                local_var_req_builder.query(&[("verified", &param_value.to_string())]);
        }
        if let Some(ref param_value) = enrollment_mode {
            local_var_req_builder = match "csv" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("enrollment_mode".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "enrollment_mode",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref param_value) = query {
            local_var_req_builder =
                local_var_req_builder.query(&[("query", &param_value.to_string())]);
        }
        if let Some(ref param_value) = order_by {
            local_var_req_builder =
                local_var_req_builder.query(&[("order_by", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganizationDomains`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OrganizationDomains`")))),
            }
        } else {
            let local_var_entity: Option<ListAllOrganizationDomainsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Get a list of all domains of an organization.
    async fn list_organization_domains<
        'organization_id,
        'verified,
        'enrollment_mode,
        'limit,
        'offset,
    >(
        &self,
        organization_id: &'organization_id str,
        verified: Option<&'verified str>,
        enrollment_mode: Option<&'enrollment_mode str>,
        limit: Option<i32>,
        offset: Option<i32>,
    ) -> Result<models::OrganizationDomains, Error<ListOrganizationDomainsError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organization_id}/domains",
            local_var_configuration.base_path,
            organization_id = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = verified {
            local_var_req_builder =
                local_var_req_builder.query(&[("verified", &param_value.to_string())]);
        }
        if let Some(ref param_value) = enrollment_mode {
            local_var_req_builder =
                local_var_req_builder.query(&[("enrollment_mode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganizationDomains`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OrganizationDomains`")))),
            }
        } else {
            let local_var_entity: Option<ListOrganizationDomainsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Updates the properties of an existing organization domain.
    async fn update_organization_domain<
        'organization_id,
        'domain_id,
        'update_organization_domain_request,
    >(
        &self,
        organization_id: &'organization_id str,
        domain_id: &'domain_id str,
        update_organization_domain_request: models::UpdateOrganizationDomainRequest,
    ) -> Result<models::OrganizationDomain, Error<UpdateOrganizationDomainError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organization_id}/domains/{domain_id}",
            local_var_configuration.base_path,
            organization_id = crate::apis::urlencode(organization_id),
            domain_id = crate::apis::urlencode(domain_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PATCH, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&update_organization_domain_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganizationDomain`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OrganizationDomain`")))),
            }
        } else {
            let local_var_entity: Option<UpdateOrganizationDomainError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`OrganizationDomainsApi::create_organization_domain`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateOrganizationDomainError {
    Status400(models::ClerkErrors),
    Status403(models::ClerkErrors),
    Status404(models::ClerkErrors),
    Status422(models::ClerkErrors),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`OrganizationDomainsApi::delete_organization_domain`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteOrganizationDomainError {
    Status400(models::ClerkErrors),
    Status401(models::ClerkErrors),
    Status404(models::ClerkErrors),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`OrganizationDomainsApi::list_all_organization_domains`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListAllOrganizationDomainsError {
    Status401(models::ClerkErrors),
    Status403(models::ClerkErrors),
    Status422(models::ClerkErrors),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`OrganizationDomainsApi::list_organization_domains`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListOrganizationDomainsError {
    Status401(models::ClerkErrors),
    Status422(models::ClerkErrors),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`OrganizationDomainsApi::update_organization_domain`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateOrganizationDomainError {
    Status400(models::ClerkErrors),
    Status404(models::ClerkErrors),
    Status422(models::ClerkErrors),
    UnknownValue(serde_json::Value),
}
