/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use super::configuration;
use super::Error;
use crate::apis::ContentType;
use crate::apis::ResponseContent;
use crate::models;
use async_trait::async_trait;
use reqwest;
use serde::de::Error as _;
use serde::Deserialize;
use serde::Serialize;
use std::sync::Arc;

#[async_trait]
pub trait OrganizationMembershipsApi: Send + Sync {
    /// POST /organizations/{organization_id}/memberships
    ///
    /// Adds a user as a member to the given organization. Only users in the same instance as the organization can be added as members.  This organization will be the user's [active organization] (https://clerk.com/docs/organizations/overview#active-organization) the next time they create a session, presuming they don't explicitly set a different organization as active before then.
    async fn create_organization_membership<
        'organization_id,
        'create_organization_membership_request,
    >(
        &self,
        organization_id: &'organization_id str,
        create_organization_membership_request: models::CreateOrganizationMembershipRequest,
    ) -> Result<models::OrganizationMembership, Error<CreateOrganizationMembershipError>>;

    /// DELETE /organizations/{organization_id}/memberships/{user_id}
    ///
    /// Removes the given membership from the organization
    async fn delete_organization_membership<'organization_id, 'user_id>(
        &self,
        organization_id: &'organization_id str,
        user_id: &'user_id str,
    ) -> Result<models::OrganizationMembership, Error<DeleteOrganizationMembershipError>>;

    /// GET /organization_memberships
    ///
    /// Retrieves all organization user memberships for the given instance.
    async fn instance_get_organization_memberships<'order_by, 'limit, 'offset>(
        &self,
        order_by: Option<&'order_by str>,
        limit: Option<i32>,
        offset: Option<i32>,
    ) -> Result<models::OrganizationMemberships, Error<InstanceGetOrganizationMembershipsError>>;

    /// GET /organizations/{organization_id}/memberships
    ///
    /// Retrieves all user memberships for the given organization
    async fn list_organization_memberships<
        'organization_id,
        'order_by,
        'user_id,
        'email_address,
        'phone_number,
        'username,
        'web3_wallet,
        'role,
        'query,
        'email_address_query,
        'phone_number_query,
        'username_query,
        'name_query,
        'last_active_at_before,
        'last_active_at_after,
        'created_at_before,
        'created_at_after,
        'limit,
        'offset,
    >(
        &self,
        organization_id: &'organization_id str,
        order_by: Option<&'order_by str>,
        user_id: Option<Vec<String>>,
        email_address: Option<Vec<String>>,
        phone_number: Option<Vec<String>>,
        username: Option<Vec<String>>,
        web3_wallet: Option<Vec<String>>,
        role: Option<Vec<String>>,
        query: Option<&'query str>,
        email_address_query: Option<&'email_address_query str>,
        phone_number_query: Option<&'phone_number_query str>,
        username_query: Option<&'username_query str>,
        name_query: Option<&'name_query str>,
        last_active_at_before: Option<i32>,
        last_active_at_after: Option<i32>,
        created_at_before: Option<i32>,
        created_at_after: Option<i32>,
        limit: Option<i32>,
        offset: Option<i32>,
    ) -> Result<models::OrganizationMemberships, Error<ListOrganizationMembershipsError>>;

    /// PATCH /organizations/{organization_id}/memberships/{user_id}
    ///
    /// Updates the properties of an existing organization membership
    async fn update_organization_membership<
        'organization_id,
        'user_id,
        'update_organization_membership_request,
    >(
        &self,
        organization_id: &'organization_id str,
        user_id: &'user_id str,
        update_organization_membership_request: models::UpdateOrganizationMembershipRequest,
    ) -> Result<models::OrganizationMembership, Error<UpdateOrganizationMembershipError>>;

    /// PATCH /organizations/{organization_id}/memberships/{user_id}/metadata
    ///
    /// Update an organization membership's metadata attributes by merging existing values with the provided parameters. Metadata values will be updated via a deep merge. Deep means that any nested JSON objects will be merged as well. You can remove metadata keys at any level by setting their value to `null`.
    async fn update_organization_membership_metadata<
        'organization_id,
        'user_id,
        'update_organization_membership_metadata_request,
    >(
        &self,
        organization_id: &'organization_id str,
        user_id: &'user_id str,
        update_organization_membership_metadata_request: Option<
            models::UpdateOrganizationMembershipMetadataRequest,
        >,
    ) -> Result<models::OrganizationMembership, Error<UpdateOrganizationMembershipMetadataError>>;
}

pub struct OrganizationMembershipsApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl OrganizationMembershipsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl OrganizationMembershipsApi for OrganizationMembershipsApiClient {
    /// Adds a user as a member to the given organization. Only users in the same instance as the organization can be added as members.  This organization will be the user's [active organization] (https://clerk.com/docs/organizations/overview#active-organization) the next time they create a session, presuming they don't explicitly set a different organization as active before then.
    async fn create_organization_membership<
        'organization_id,
        'create_organization_membership_request,
    >(
        &self,
        organization_id: &'organization_id str,
        create_organization_membership_request: models::CreateOrganizationMembershipRequest,
    ) -> Result<models::OrganizationMembership, Error<CreateOrganizationMembershipError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organization_id}/memberships",
            local_var_configuration.base_path,
            organization_id = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&create_organization_membership_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganizationMembership`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OrganizationMembership`")))),
            }
        } else {
            let local_var_entity: Option<CreateOrganizationMembershipError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Removes the given membership from the organization
    async fn delete_organization_membership<'organization_id, 'user_id>(
        &self,
        organization_id: &'organization_id str,
        user_id: &'user_id str,
    ) -> Result<models::OrganizationMembership, Error<DeleteOrganizationMembershipError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organization_id}/memberships/{user_id}",
            local_var_configuration.base_path,
            organization_id = crate::apis::urlencode(organization_id),
            user_id = crate::apis::urlencode(user_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganizationMembership`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OrganizationMembership`")))),
            }
        } else {
            let local_var_entity: Option<DeleteOrganizationMembershipError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves all organization user memberships for the given instance.
    async fn instance_get_organization_memberships<'order_by, 'limit, 'offset>(
        &self,
        order_by: Option<&'order_by str>,
        limit: Option<i32>,
        offset: Option<i32>,
    ) -> Result<models::OrganizationMemberships, Error<InstanceGetOrganizationMembershipsError>>
    {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organization_memberships",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = order_by {
            local_var_req_builder =
                local_var_req_builder.query(&[("order_by", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganizationMemberships`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OrganizationMemberships`")))),
            }
        } else {
            let local_var_entity: Option<InstanceGetOrganizationMembershipsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves all user memberships for the given organization
    async fn list_organization_memberships<
        'organization_id,
        'order_by,
        'user_id,
        'email_address,
        'phone_number,
        'username,
        'web3_wallet,
        'role,
        'query,
        'email_address_query,
        'phone_number_query,
        'username_query,
        'name_query,
        'last_active_at_before,
        'last_active_at_after,
        'created_at_before,
        'created_at_after,
        'limit,
        'offset,
    >(
        &self,
        organization_id: &'organization_id str,
        order_by: Option<&'order_by str>,
        user_id: Option<Vec<String>>,
        email_address: Option<Vec<String>>,
        phone_number: Option<Vec<String>>,
        username: Option<Vec<String>>,
        web3_wallet: Option<Vec<String>>,
        role: Option<Vec<String>>,
        query: Option<&'query str>,
        email_address_query: Option<&'email_address_query str>,
        phone_number_query: Option<&'phone_number_query str>,
        username_query: Option<&'username_query str>,
        name_query: Option<&'name_query str>,
        last_active_at_before: Option<i32>,
        last_active_at_after: Option<i32>,
        created_at_before: Option<i32>,
        created_at_after: Option<i32>,
        limit: Option<i32>,
        offset: Option<i32>,
    ) -> Result<models::OrganizationMemberships, Error<ListOrganizationMembershipsError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organization_id}/memberships",
            local_var_configuration.base_path,
            organization_id = crate::apis::urlencode(organization_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = order_by {
            local_var_req_builder =
                local_var_req_builder.query(&[("order_by", &param_value.to_string())]);
        }
        if let Some(ref param_value) = user_id {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("user_id".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "user_id",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref param_value) = email_address {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("email_address".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "email_address",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref param_value) = phone_number {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("phone_number".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "phone_number",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref param_value) = username {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("username".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "username",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref param_value) = web3_wallet {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("web3_wallet".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "web3_wallet",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref param_value) = role {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .into_iter()
                        .map(|p| ("role".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "role",
                    &param_value
                        .into_iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref param_value) = query {
            local_var_req_builder =
                local_var_req_builder.query(&[("query", &param_value.to_string())]);
        }
        if let Some(ref param_value) = email_address_query {
            local_var_req_builder =
                local_var_req_builder.query(&[("email_address_query", &param_value.to_string())]);
        }
        if let Some(ref param_value) = phone_number_query {
            local_var_req_builder =
                local_var_req_builder.query(&[("phone_number_query", &param_value.to_string())]);
        }
        if let Some(ref param_value) = username_query {
            local_var_req_builder =
                local_var_req_builder.query(&[("username_query", &param_value.to_string())]);
        }
        if let Some(ref param_value) = name_query {
            local_var_req_builder =
                local_var_req_builder.query(&[("name_query", &param_value.to_string())]);
        }
        if let Some(ref param_value) = last_active_at_before {
            local_var_req_builder =
                local_var_req_builder.query(&[("last_active_at_before", &param_value.to_string())]);
        }
        if let Some(ref param_value) = last_active_at_after {
            local_var_req_builder =
                local_var_req_builder.query(&[("last_active_at_after", &param_value.to_string())]);
        }
        if let Some(ref param_value) = created_at_before {
            local_var_req_builder =
                local_var_req_builder.query(&[("created_at_before", &param_value.to_string())]);
        }
        if let Some(ref param_value) = created_at_after {
            local_var_req_builder =
                local_var_req_builder.query(&[("created_at_after", &param_value.to_string())]);
        }
        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganizationMemberships`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OrganizationMemberships`")))),
            }
        } else {
            let local_var_entity: Option<ListOrganizationMembershipsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Updates the properties of an existing organization membership
    async fn update_organization_membership<
        'organization_id,
        'user_id,
        'update_organization_membership_request,
    >(
        &self,
        organization_id: &'organization_id str,
        user_id: &'user_id str,
        update_organization_membership_request: models::UpdateOrganizationMembershipRequest,
    ) -> Result<models::OrganizationMembership, Error<UpdateOrganizationMembershipError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organization_id}/memberships/{user_id}",
            local_var_configuration.base_path,
            organization_id = crate::apis::urlencode(organization_id),
            user_id = crate::apis::urlencode(user_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PATCH, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&update_organization_membership_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganizationMembership`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OrganizationMembership`")))),
            }
        } else {
            let local_var_entity: Option<UpdateOrganizationMembershipError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Update an organization membership's metadata attributes by merging existing values with the provided parameters. Metadata values will be updated via a deep merge. Deep means that any nested JSON objects will be merged as well. You can remove metadata keys at any level by setting their value to `null`.
    async fn update_organization_membership_metadata<
        'organization_id,
        'user_id,
        'update_organization_membership_metadata_request,
    >(
        &self,
        organization_id: &'organization_id str,
        user_id: &'user_id str,
        update_organization_membership_metadata_request: Option<
            models::UpdateOrganizationMembershipMetadataRequest,
        >,
    ) -> Result<models::OrganizationMembership, Error<UpdateOrganizationMembershipMetadataError>>
    {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/organizations/{organization_id}/memberships/{user_id}/metadata",
            local_var_configuration.base_path,
            organization_id = crate::apis::urlencode(organization_id),
            user_id = crate::apis::urlencode(user_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PATCH, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder =
            local_var_req_builder.json(&update_organization_membership_metadata_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganizationMembership`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::OrganizationMembership`")))),
            }
        } else {
            let local_var_entity: Option<UpdateOrganizationMembershipMetadataError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`OrganizationMembershipsApi::create_organization_membership`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateOrganizationMembershipError {
    Status400(models::ClerkErrors),
    Status403(models::ClerkErrors),
    Status404(models::ClerkErrors),
    Status422(models::ClerkErrors),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`OrganizationMembershipsApi::delete_organization_membership`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteOrganizationMembershipError {
    Status401(models::ClerkErrors),
    Status404(models::ClerkErrors),
    Status422(models::ClerkErrors),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`OrganizationMembershipsApi::instance_get_organization_memberships`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InstanceGetOrganizationMembershipsError {
    Status400(models::ClerkErrors),
    Status401(models::ClerkErrors),
    Status422(models::ClerkErrors),
    Status500(models::ClerkErrors),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`OrganizationMembershipsApi::list_organization_memberships`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListOrganizationMembershipsError {
    Status401(models::ClerkErrors),
    Status422(models::ClerkErrors),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`OrganizationMembershipsApi::update_organization_membership`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateOrganizationMembershipError {
    Status404(models::ClerkErrors),
    Status422(models::ClerkErrors),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`OrganizationMembershipsApi::update_organization_membership_metadata`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateOrganizationMembershipMetadataError {
    Status400(models::ClerkErrors),
    Status404(models::ClerkErrors),
    Status422(models::ClerkErrors),
    UnknownValue(serde_json::Value),
}
