/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2025-04-10
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use super::configuration;
use super::Error;
use crate::apis::ContentType;
use crate::apis::ResponseContent;
use crate::models;
use async_trait::async_trait;
use reqwest;
use serde::de::Error as _;
use serde::Deserialize;
use serde::Serialize;
use std::sync::Arc;

#[async_trait]
pub trait WaitlistEntriesApi: Send + Sync {
    /// POST /waitlist_entries
    ///
    /// Creates a new waitlist entry for the given email address. If the email address is already on the waitlist, no new entry will be created and the existing waitlist entry will be returned.
    async fn create_waitlist_entry<'create_waitlist_entry_request>(
        &self,
        create_waitlist_entry_request: Option<models::CreateWaitlistEntryRequest>,
    ) -> Result<models::WaitlistEntry, Error<CreateWaitlistEntryError>>;

    /// DELETE /waitlist_entries/{waitlist_entry_id}
    ///
    /// Delete a pending waitlist entry.
    async fn delete_waitlist_entry<'waitlist_entry_id>(
        &self,
        waitlist_entry_id: &'waitlist_entry_id str,
    ) -> Result<models::DeletedObject, Error<DeleteWaitlistEntryError>>;

    /// POST /waitlist_entries/{waitlist_entry_id}/invite
    ///
    /// Send an invite to the email address in a waitlist entry.
    async fn invite_waitlist_entry<'waitlist_entry_id, 'invite_waitlist_entry_request>(
        &self,
        waitlist_entry_id: &'waitlist_entry_id str,
        invite_waitlist_entry_request: Option<models::InviteWaitlistEntryRequest>,
    ) -> Result<models::WaitlistEntry, Error<InviteWaitlistEntryError>>;

    /// GET /waitlist_entries
    ///
    /// Retrieve a list of waitlist entries for the instance. Entries are ordered by creation date in descending order by default. Supports filtering by email address or status and pagination with limit and offset parameters.
    async fn list_waitlist_entries<'limit, 'offset, 'query, 'status, 'order_by>(
        &self,
        limit: Option<i32>,
        offset: Option<i32>,
        query: Option<&'query str>,
        status: Option<&'status str>,
        order_by: Option<&'order_by str>,
    ) -> Result<models::ListWaitlistEntries200Response, Error<ListWaitlistEntriesError>>;

    /// POST /waitlist_entries/{waitlist_entry_id}/reject
    ///
    /// Reject a waitlist entry.
    async fn reject_waitlist_entry<'waitlist_entry_id>(
        &self,
        waitlist_entry_id: &'waitlist_entry_id str,
    ) -> Result<models::WaitlistEntry, Error<RejectWaitlistEntryError>>;
}

pub struct WaitlistEntriesApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl WaitlistEntriesApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl WaitlistEntriesApi for WaitlistEntriesApiClient {
    /// Creates a new waitlist entry for the given email address. If the email address is already on the waitlist, no new entry will be created and the existing waitlist entry will be returned.
    async fn create_waitlist_entry<'create_waitlist_entry_request>(
        &self,
        create_waitlist_entry_request: Option<models::CreateWaitlistEntryRequest>,
    ) -> Result<models::WaitlistEntry, Error<CreateWaitlistEntryError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/waitlist_entries", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&create_waitlist_entry_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WaitlistEntry`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::WaitlistEntry`")))),
            }
        } else {
            let local_var_entity: Option<CreateWaitlistEntryError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Delete a pending waitlist entry.
    async fn delete_waitlist_entry<'waitlist_entry_id>(
        &self,
        waitlist_entry_id: &'waitlist_entry_id str,
    ) -> Result<models::DeletedObject, Error<DeleteWaitlistEntryError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/waitlist_entries/{waitlist_entry_id}",
            local_var_configuration.base_path,
            waitlist_entry_id = crate::apis::urlencode(waitlist_entry_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeletedObject`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::DeletedObject`")))),
            }
        } else {
            let local_var_entity: Option<DeleteWaitlistEntryError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Send an invite to the email address in a waitlist entry.
    async fn invite_waitlist_entry<'waitlist_entry_id, 'invite_waitlist_entry_request>(
        &self,
        waitlist_entry_id: &'waitlist_entry_id str,
        invite_waitlist_entry_request: Option<models::InviteWaitlistEntryRequest>,
    ) -> Result<models::WaitlistEntry, Error<InviteWaitlistEntryError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/waitlist_entries/{waitlist_entry_id}/invite",
            local_var_configuration.base_path,
            waitlist_entry_id = crate::apis::urlencode(waitlist_entry_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&invite_waitlist_entry_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WaitlistEntry`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::WaitlistEntry`")))),
            }
        } else {
            let local_var_entity: Option<InviteWaitlistEntryError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieve a list of waitlist entries for the instance. Entries are ordered by creation date in descending order by default. Supports filtering by email address or status and pagination with limit and offset parameters.
    async fn list_waitlist_entries<'limit, 'offset, 'query, 'status, 'order_by>(
        &self,
        limit: Option<i32>,
        offset: Option<i32>,
        query: Option<&'query str>,
        status: Option<&'status str>,
        order_by: Option<&'order_by str>,
    ) -> Result<models::ListWaitlistEntries200Response, Error<ListWaitlistEntriesError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/waitlist_entries", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = limit {
            local_var_req_builder =
                local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder =
                local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref param_value) = query {
            local_var_req_builder =
                local_var_req_builder.query(&[("query", &param_value.to_string())]);
        }
        if let Some(ref param_value) = status {
            local_var_req_builder =
                local_var_req_builder.query(&[("status", &param_value.to_string())]);
        }
        if let Some(ref param_value) = order_by {
            local_var_req_builder =
                local_var_req_builder.query(&[("order_by", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListWaitlistEntries200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ListWaitlistEntries200Response`")))),
            }
        } else {
            let local_var_entity: Option<ListWaitlistEntriesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Reject a waitlist entry.
    async fn reject_waitlist_entry<'waitlist_entry_id>(
        &self,
        waitlist_entry_id: &'waitlist_entry_id str,
    ) -> Result<models::WaitlistEntry, Error<RejectWaitlistEntryError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/waitlist_entries/{waitlist_entry_id}/reject",
            local_var_configuration.base_path,
            waitlist_entry_id = crate::apis::urlencode(waitlist_entry_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WaitlistEntry`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::WaitlistEntry`")))),
            }
        } else {
            let local_var_entity: Option<RejectWaitlistEntryError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`WaitlistEntriesApi::create_waitlist_entry`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateWaitlistEntryError {
    Status400(models::ClerkErrors),
    Status422(models::ClerkErrors),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`WaitlistEntriesApi::delete_waitlist_entry`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteWaitlistEntryError {
    Status400(models::ClerkErrors),
    Status404(models::ClerkErrors),
    Status409(models::ClerkErrors),
    Status422(models::ClerkErrors),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`WaitlistEntriesApi::invite_waitlist_entry`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InviteWaitlistEntryError {
    Status400(models::ClerkErrors),
    Status404(models::ClerkErrors),
    Status409(models::ClerkErrors),
    Status422(models::ClerkErrors),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`WaitlistEntriesApi::list_waitlist_entries`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListWaitlistEntriesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`WaitlistEntriesApi::reject_waitlist_entry`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RejectWaitlistEntryError {
    Status400(models::ClerkErrors),
    Status404(models::ClerkErrors),
    Status409(models::ClerkErrors),
    Status422(models::ClerkErrors),
    UnknownValue(serde_json::Value),
}
