[package]
name = "common-core"
version = "100.0.0"
edition = "2024"

[features]
default = ["serde", "argon2"]
argon2 = ["dep:argon2"]
serde = ["dep:serde", "dep:serde_json"]

[dependencies]
anyhow.workspace = true
argon2 = { workspace = true, optional = true }
axum.workspace = true
base64ct = { version = "1", features = ["alloc"] }
clerk-client = { path = "../clerk/" }
jsonwebtoken.workspace = true
rand.workspace = true
rust_decimal.workspace = true
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tonic.workspace = true
tower-http.workspace = true
tower.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
