CREATE TYPE IF NOT EXISTS currency_status AS ENUM ('ACTIVE', 'INACTIVE', 'DEPRECATED');
CREATE TABLE IF NOT EXISTS currencies (
    id SERIAL PRIMARY KEY,
    symbol CHAR(9) NOT NULL UNIQUE,
    name TEXT NOT NULL,
    status currency_status NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX idx_symbol ON currencies (symbol);