CREATE TABLE IF NOT EXISTS btc_deposit_addresses (
    id BIGSERIAL PRIMARY KEY,
    address TEXT NOT NULL,
    user_id UUID NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(address, user_id)
);
